site_name: cxy's blog 

repo_url: https://github.com/ChuXiaoYi
site_url: http:// www.chuxiaoyi.cn
google_analytics: ['UA-36723568-3', 'mkdocs.org']

site_author: 褚晓逸

copyright: "author by ChuXiaoYi"

nav:
  - 日常问题: daily_problem.md
  - django相关:
    - django开发实战1: django/django.md
    - django开发实战2: django/django2.md
    - django-rest-framework学习笔记: 
      - Serialization: django/django_rest_framework/djang_rest_framework.md
      - Requests and responses: django/django_rest_framework/django_rest_framework_responseAndRequest.md
      - 基于类的视图: django/django_rest_framework/django_rest_framework_ClassBasedViews.md
  - python3.7标准库相关记录:
    - functools: python3.7_standard_library/py3标准库——functools.md
    - itertools: python3.7_standard_library/py3标准库——itertools.md
    - collections: python3.7_standard_library/py3标准库——collections.md
  - 计算字符串相似度相关方法: calculate_similiar.md
  - celery:
    - celery快速入门: celery/celery-01.md
    - celery进阶: celery/celery-02.md
  - vim:
      - vim简单入门: vim/vim-01.md

site_favicon: favicon.ico

theme:
    name: material
    # custom_dir: custom_theme/
    highlightjs: true
    hljs_style: github
    hljs_languages:
        - yaml
        - rust
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true 
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
  social:
    - type: 'github'
      link: 'https://github.com/ChuXiaoYi?tab=repositories' 
    - type: 'book'
      link: 'https://blog.csdn.net/weixin_40156487'
  disqus: 'chuxiaoyi'
